 - name: Install Maven
   ansible.builtin.dnf:
     name: maven
     state: present

 - name: Load App Prerequisites
   ansible.builtin.include_tasks:
     file: app_prerequisites.yml

 - name: Build the shipping application using Maven
   ansible.builtin.shell: mvn clean package; mv target/{{ app_name }}-1.0.jar {{ app_name }}.jar
   args:
     chdir: /app

 - name: Systemd Set-Up
   ansible.builtin.include_tasks:
     file: systemd_setup.yml    
