     - name: Copy file to web root
       ansible.builtin.template:
         src: "{{ app_name}}.service"
         dest: /etc/systemd/system/{{ app_name}}.service
     
     - name: Start the service
       ansible.builtin.systemd_service:
         name: "{{ app_name}}.service"
         state: restarted
         enabled: yes
         daemon_reload: yes


