#dnf install python3 gcc python3-devel -y
#useradd roboshop
#mkdir /app 
#curl -L -o /tmp/payment.zip https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
#cd /app 
#unzip /tmp/payment.zip
#cd /app 
#pip3 install -r requirements.txt
#/etc/systemd/system/payment.service
#systemctl daemon-reload
#systemctl enable payment 
#systemctl start payment
 - name: Setup Payment host
   hosts: 172.31.36.196
   become: true
   tasks:
     - name: Set prompt
       ansible.builtin.shell: set-prompt payment

     - name: Install Python and required components
       ansible.builtin.dnf:
         name: "{{ item }}"
         state: present       
       loop:
         - python3
         - gcc
         - python3-devel
         - python3-pip
     - name: Create a user 'roboshop' with a home directory
       ansible.builtin.user:
         name: roboshop
      
     - name: Create a directory if it does not exist
       ansible.builtin.file:
         path: /app 
         state: directory

    
     - name: Copy payment.service file to /etc/systemd/system/
       ansible.builtin.template:
         src: payment.service
         dest: /etc/systemd/system/payment.service

     - name: Download payment
       ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
         dest: /tmp/payment.zip

     - name: Extract catalogue-v3.zip into /usr/share/nginx/html
       ansible.builtin.unarchive:
         src:  /tmp/payment.zip
         dest: /app
         remote_src: yes
     - name: Install requirements on payment host
       ansible.builtin.pip:
         requirements: /app/requirements.txt
         executable: pip3
           #     - name: Install requirements on payment host
           #  ansible.builtin.command: pip3 install -r requirements.txt
 
          
     - name: Reload service daemon-reload, in all cases
       ansible.builtin.command: systemctl daemon-reload
         
     - name: Start the service
       ansible.builtin.systemd_service:
         name: payment
         state: started
         enabled: yes         
