#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#dnf install nodejs -y
#useradd roboshop
#mkdir /app 
#curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
#cd /app 
#unzip /tmp/user.zip
#cd /app 
#npm install 
#/etc/systemd/system/user.service
#systemctl daemon-reload
#systemctl enable user 
#systemctl start user

 - name: Configure user host
   hosts: 172.31.47.121
   become: true
   tasks: 
     
     - name: Set prompt
       ansible.builtin.shell: set-prompt user
     
     - name: Disable nodejs modules first
       ansible.builtin.command: dnf module disable nodejs -y
    
     - name: Enable nodejs modules
       ansible.builtin.command: dnf module enable nodejs:20 -y

     - name: Install nodejs:20 on frontend
       ansible.builtin.dnf:
         name: nodejs
         state: installed
      
     - name: Create a user 'roboshop' with a home directory
       ansible.builtin.user:
         name: roboshop
      
     - name: Create a directory if it does not exist
       ansible.builtin.file:
         path: /app 
         state: directory

    
     - name: Copy user.service file to /etc/systemd/system/
       ansible.builtin.template:
         src: user.service
         dest: /etc/systemd/system/user.service

     - name: Download user.zip
       ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
         dest: /tmp/user.zip

     - name: Extract user.zip into /tmp 
       ansible.builtin.unarchive:
         src:  /tmp/user.zip
         dest: /app 
         remote_src: yes

     - name: Install npm on catalogue
       ansible.builtin.command: npm install    
       args:
         chdir: /app
          
     - name: Reload service daemon-reload, in all cases
       ansible.builtin.command: systemctl daemon-reload
   
     - name: Start the service
       ansible.builtin.systemd_service:
         name: user
         state: started
         enabled: yes
