default:
	git pull
	ansible-playbook -i $(app_name)-$(env).chatgpt1.info, -e ansible_user=ec2-user -e ansible_password=DevOps321 -e env=$(env) -e app_name=$1 roboshop.yml


#default:
#	git pull
#	echo ansible-playbook -i $(app_name)-$(env).rdevopsb81.online, -e ansible_user=ec2-user -e ansible_password=DevOps321 -e env=$(env) -e app_name=$1 roboshop.yml





#to run the make file 
# app_name=redis env=dev make
#app_name=user env=dev make



