 - name: Disable nodejs modules first
   ansible.builtin.command: dnf module disable nodejs -y

 - name: Enable nodejs modules
   ansible.builtin.command: dnf module enable nodejs:20 -y

 - name: Install nodejs:20  
   ansible.builtin.dnf:
     name: nodejs
     state: installed
  
 - name: Load App Prerequisites
   ansible.builtin.include.tasks:
     file: app_prerequisites.yml

 - name: Install npm on catalogue
   ansible.builtin.command: npm install
   args:
     chdir: /app

 - name: SystemD setup
   ansible.builtin.include_tasks:
     file: systemd_setup.yml   